using System;
using System.ComponentModel.DataAnnotations;

namespace VentureCarRentals.Models
{
    public class RentalAgreement
    {
        public int RentalAgreementId { get; set; }

        [Required]
        public int BookingId { get; set; }

        // Stores the rental agreement text accepted by the user online.
        [Required]
        public string AgreementText { get; set; } = "";

        // online_accepted = user accepted agreement online
        // signed_uploaded = admin uploaded the signed face-to-face agreement
        // approved = admin approved the booking after checking the signed agreement
        // cancelled = booking/agreement was cancelled
        [Required]
        public string Status { get; set; } = "online_accepted";

        // Date and time when the user accepted the agreement online.
        public DateTime? OnlineAcceptedAt { get; set; }

        // Blank agreement generated by the system for admin to download/print.
        public string? GeneratedAgreementFileUrl { get; set; }

        // Date and time when the blank agreement was generated.
        public DateTime? GeneratedAt { get; set; }

        // Signed agreement uploaded by admin after face-to-face signing.
        public string? SignedAgreementFileUrl { get; set; }

        // Date and time when admin uploaded the signed agreement.
        public DateTime? SignedUploadedAt { get; set; }

        // Date and time when admin approved the agreement.
        public DateTime? ApprovedAt { get; set; }

        public Booking? Booking { get; set; }
    }
}